[package]
name = "zoid_ast"
version = "0.1.0"
edition = "2021"

authors = ["Jacob Evans <jacob@jwevans.dev>"]

[dependencies]
bumpalo = { version = "3.15.3", features = ["allocator-api2"] }
hashbrown = "0.14.3"
zoid_lexer = { path = "../zoid_lexer" }
zoid_location = { path = "../zoid_location" }
