[package]
name = "zoid_lexer"
version = "0.1.0"
edition = "2021"

authors = ["Jacob Evans <jacob@jwevans.dev>"]

[dependencies]
zoid_location = { path = "../zoid_location" }

[dev-dependencies]
expect-test = "1.4.1"

