[package]
name = "zoid_hlir"
description = "Zoid Language High Level Intermediate Representation"
authors = ["Jacob Evans <jacob@jwevans.dev>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
