[package]
name = "zoidc"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.15.1"
clap = { version = "4.5.1", features = ["derive", "wrap_help"] }

zoid_parser = { path = "../zoid_parser" }
